### ISSUE TITLE
getting openpixel up and running

### ISSUE THREAD

**Issue by David-E-Alvarez** [dockwa/openpixel#151]
Hi guys. I am went through the "setup and customize" steps for my Gatsby personal website e.g. ran `npm i openpixel` but still is unclear about how the tracking actually happens besides just putting the code on a page where I want to do the collecting/tracking. Thank you.

**Comment by stuyam** [comment]
openpixel is only the front end piece of the equation to send tracking events to any url. It is agnostic to how you store and track those requests on the backend. See #48
