### ISSUE TITLE
onclick events

### ISSUE THREAD

**Issue by fkeymantics** [dockwa/openpixel#2]
In setup.js it would be much better to use addEventListener rather than overriding the onclick event which leads to breaking most of the website you might put the pixel on.

Regards

**Comment by stuyam** [comment]
Thanks for the suggestion @fkeymantics that makes total sense. Feel free to open a pull request or I can take a what at it when I get a chance.

**Comment by stuyam** [comment]
Thanks @fkeymantics this is updated in the most recent commit! https://github.com/dockwa/openpixel/commit/ca7a034bacdc228efe2dd17e6ec59c7da63b5d2e
