### ISSUE TITLE
Tracking pageview in a SPA

### ISSUE THREAD

**Issue by dottodot** [dockwa/openpixel#24]
I trying to add page tracking for a SPA (Angular) but can't seem to get it to work. I can get other events to work but not `pageload`. For example triggering the following event on a route change in my app doesn't send out the event, the only time is does work is on the first page load. 

```
opix('event', 'pageload');
```

**Comment by boralp** [comment]
Maybe you should divide your inpage requests into a new event like

`opix('event', 'pageload');`

**Comment by elrumordelaluz** [comment]
Is there any reason on why when switching route and calling manually `opix('event', 'pageload')` doesn't work, but passing a custom event like `opix('event', 'pageload2')` works? Furthermore, in the latter there isn't `rl` present.

Thanks,
