### ISSUE TITLE
Set utm_source, utm_source, utm_medium ...

### ISSUE THREAD

**Issue by oscarrosado** [dockwa/openpixel#3]
Hello,
How can you set utm_source, utm_source, utm_medium ...?
Thank you!

**Comment by stuyam** [comment]
What exactly are you trying to accomplish? The utms from the url are saved as cookies to the pages and sent as parameters in the pixel request. If you want to set them you could set utms in the url but those meant to track where the url came from. So if you are linking to a page with openpixel you could put the utms in the url like `?utm_source=something`.

Internally this is how it works. The utms are set automatically to cookies when the pages loads here: https://github.com/dockwa/openpixel/blob/ca7a034bacdc228efe2dd17e6ec59c7da63b5d2e/src/setup.js#L4
Which sets the utms as cookies on the browser: https://github.com/dockwa/openpixel/blob/9013707d40476f426614787175a1ba0865927c89/src/cookie.js#L42-L61
Then when the pixel requests are fired the utms are sent from the stored cookies: https://github.com/dockwa/openpixel/blob/9013707d40476f426614787175a1ba0865927c89/src/pixel.js#L38-L42

Let me know if you have any questions 😄

**Comment by oscarrosado** [comment]
Ok, I get it.

The question arose for the following reason:

Having availability to configure different parameters of the url and generate a url with utm but without values ...

    &utm_source=&utm_medium=&utm_term=&utm_content=&utm_campaign=

I thought that there was the possibility of configuring also the different utm.

Perfect then, thank you very much! And congratulations for the development, it's fantastic.
