### ISSUE TITLE
Is it necessary to append the pixel to the body vs doing something like (new Image()).src= pixel_url

### ISSUE THREAD

**Issue by mevinbabuc** [dockwa/openpixel#4]
https://github.com/dockwa/openpixel/blob/ca7a034bacdc228efe2dd17e6ec59c7da63b5d2e/src/pixel.js#L68

Are there advantages of appending the pixel to the body, vs just initiating the download by creating a new Image Object ?

**Comment by stuyam** [comment]
Good question @mevinbabuc I have no idea lol. Does doing `(new Image()).src= pixel_url` work in most browsers and initial a download without adding it to the page?
