### ISSUE TITLE
Sending Event Data to DB

### ISSUE THREAD

**Issue by dundas** [dockwa/openpixel#60]
Thanks for open sourcing this. It's really a great project. 

I had a question about how you implement. Where's the best place to send the tracking data to? Do you have it call an open rest api which stores the data to the DB? 

If so, where would I call the api from? 

Thanks again!

**Comment by stuyam** [comment]
We send it to a server where we log the http request and then process the log files async to keep the requests fast. But you could have it create database records or anything like that, it can fire a lot of events so performance is the only concern.

**Comment by dundas** [comment]
Got it thanks!
