### ISSUE TITLE
Video Tracking

### ISSUE THREAD

**Issue by robadmin** [dockwa/openpixel#75]
Would be cool to track how long someone spent watching video(s) that are on displayed on the websites. Most popular targets could be youtube and vimeo. The idea would be to get data passed back similar to https://plugins.matomo.org/MediaAnalytics, just without the fancy interface.

**Comment by stuyam** [comment]
You can definitely do this in a manual way. Check out the events api: https://github.com/dockwa/openpixel#events

You could do something like:
```javascript
opix('event', 'video_play, {video_id: 1234})
opix('event', 'video_pause', {video_id: 1234})
```
Here then have some of the data to pull out from params here: https://github.com/dockwa/openpixel#tracking-data

You could use the `ev` to get the event name 'video_play', the `ts` timestamp param from the pixel sends to see how long the video was played, and the `ed` to get the event data to see which video it was about for example. Or it may be easier to send it as one event showing how many seconds the video was played:
```javacript
opix('event', 'video_play_duration, {duration: '243s', video_id: 1234})
```
